### ISSUE TITLE
Baza userów z całego świata na sp-dmr.pl jest bardziej aktualna

### ISSUE THREAD

**Issue by SP5TA** [satanowski/cnt4gd77#4]
Zauważyłem że baza ta jest o ok 800 kontaktów w skali swiata większa od generowanej przez marc

**Comment by satanowski** [comment]
Bardziej aktualna niż która?
Ta która jest na  sp-dmr.pl tylko link do http://dmr.ham-digital.net/user_by_call.php?id=260.
I tego właśnie używam. Czy może jest jeszcze jakiś inny addres?
